base_url = "https://chewdata.github.io/"
title = "ChewData"
description = "ChewData is a light ETL in Rust"

compile_sass = true
highlight_code = true
insert_anchor_links = true
highlight_theme = "kronuz"
build_search_index = true

[extra]
author = "Jean-Marc Fiaschi"
