---
name: docker-release

on: push

env:
  CARGO_TERM_COLOR: always
  CHEWDATA_TAG: latest

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: cp .env.ci .env
      - run: CHEWDATA_TAG=$(make version) && echo "CHEWDATA_TAG=$CHEWDATA_TAG" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/chewdata:${{ env.CHEWDATA_TAG }}
      - run: echo ${{ steps.docker_build.outputs.digest }}
